{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.name" . }}-permissions
  labels:
{{ include "capacity.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "capacity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "capacity.name" . }}-nodepod-permissions
  apiGroup: rbac.authorization.k8s.io
{{- end }}