apiVersion: v1
kind: ConfigMap
metadata:
  name: analyze-config
data:
  config.yaml: |
   logging:
     level: debug
     formatter: TXT
   plugin:
     check_interval: 30s
     check_timeout: 10s
     cloud_provider_type: {{ .Values.cloudProviderType }}
     aws_access_key_id: {{ .Values.aws.accessKeyId }}
     aws_secret_access_key: {{ .Values.aws.secretAccessKey }}
     aws_region: {{ .Values.aws.region }}
   api:
     server_host: "0.0.0.0"
     server_port: {{ .Values.service.internalPort }}
   etcd:
     endpoints:

